### ISSUE TITLE
Mentorship UX

### ISSUE THREAD

**Issue by mhaidarhanif** [bearmentor/bearmentor.com#9]
# Feature request

## Is your feature request related to a problem? Please describe.

Mentorship UX flow that increase the chance of long term connection, while also reducing the risk of abandoned conversation.

The approach in Bearmentor to solve the main problems first, is to allow manual approach for some complexity, before the development-time consuming automated system.

Prerequisites:

1. Both Mentor and Mentee have accept the deal with the prefered method of payment first. Payment can start with manual bank transfer.
2. Either Mentor or Mentee has to propose first and both accept the schedule with a calendar platform. Can be custom available schedules with daily, weekly, or monthly range. Booking the schedule can start with manual 3rd party platform like Cal.com or Calendly, connected to Google Calendar.
3. Mentor can make sure to setup the online video call room or physical onsite room location, only if the mentorship want to be done in sync, not async. If online, can start with manual setup on Zoom/Meet/Around/inLive/Jitsi/etc. If onsite, can set the address manually on the schedule.
4. Mentorship is being done with the proposed deal, schedule, and online/onsite room.
5. Mentorship progress and time is being tracked along the way, manually by the mentor first.

## Describe the solution you'd like

- [x] #10
- [ ] #11
- [ ] 3. User selects and send a request to the Services/Programs offered by the Mentor, whether free or paid. By default, every Mentor would have a Free Consultation Service.
- [ ] 4. Mentor can accept or reject the request. Because there might be too many requests at once.
- [ ] 5. Mentor and prospective Mentee have an initial discussions/chats/messaging to get to know each other and clarify the goal.
- [ ] 6. Upon agreement, mentorship can begin. If free, it starts immediately. If paid, payment has to be processed first, currently through manual bank transfer.
- [ ] 7. Bearmentor receives 10% of the payment, while the Mentor gets 90% deposited into their Balance.
- [ ] 8. Mentors can request a cashout, the process might take quickly in 1-2 days or up to 7-14 days.
- [ ] 9. Mentor and Mentee are engaging in a mentorship. Scheduling sessions for online calls, direct meetups, or text-based without any particular schedule.

## List of some more information

- User profile: to verify credibility, preferred tech stack, provide Services/Programs, request selected service for mentoring.
- User notification: Service request (accept/reject), currently manually checked without email notifications.
- Chats/messages: Open for accepted mentees or other users.
- Mentorship flow: Accept request from chosen service, chat, payment, schedule/reschedule to calendar, session reminder, call room URL or location (offline/online/Zoom/Meet/Around/etc).
- User dashboard: incoming/outgoing mentorship request, mentorship schedules, mentorship history, mentorship connection list, incoming/outgoing transactions, balance and request to cash out, availability status (active/inactive).

## Additional context

Other references:

- ADPList, has a mentorship flow but only free at the moment
- Codementor, has a mentorship flow but only paid services
- Gumroad, cashout every Friday
- Upwork, cashout with some requirements

**Comment by mhaidarhanif** [comment]
I'm hoping to finish this, at least the most essential parts first, by the end of August 2023.

**Comment by dreamid27** [comment]
Hooh, interesting product. 

how to contribute ?

**Comment by tyohan** [comment]
Another option to book the mentor schedule and easier for scheduling a video call using calendar system is using similar flow like Calendly. Basically a mentor can have a weekly schedule that available to book by the mentee.

The current flow also can be use for video call as well. So no issue with the current flow.

**Comment by mhaidarhanif** [comment]
@tyohan Yes, I've just added your comment into the initial details in the first comment, to address the booking/calendar system and the flow with a video call.

**Comment by dreamid27** [comment]
> @dreamid27 There will be a CONTRIBUTING.md file to explain "how to contribute". At the moment, can understand the repo first by cloning and following the README. Just wait until the repo is more ready for public contribution.

Got it, thanks btw
